export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/chat/index',
    'pages/daily/index',
    'pages/community/index',
    'pages/settings/index',
    'pages/login/index',
    'pages/bazi/index',
    'pages/bazi-result/index',
    'pages/membership/index',
    'pages/ziwei/index',
    'pages/ziwei-result/index',
    'pages/tarot/index',
    'pages/tarot-result/index',
    'pages/liuyao/index',
    'pages/liuyao-result/index',
    'pages/qimen/index',
    'pages/qimen-result/index',
    'pages/daliuren/index',
    'pages/daliuren-result/index',
    'pages/hepan/index',
    'pages/hepan-result/index',
    'pages/face/index',
    'pages/palm/index',
    'pages/mbti/index',
  ],
  tabBar: {
    custom: true,
    color: '#999999',
    selectedColor: '#1a1a2e',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/index/index', text: '占卜' },
      { pagePath: 'pages/chat/index', text: '对话' },
      { pagePath: 'pages/daily/index', text: '日运' },
      { pagePath: 'pages/community/index', text: '社区' },
      { pagePath: 'pages/settings/index', text: '我的' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#1a1a2e',
    navigationBarTitleText: '易有吉',
    navigationBarTextStyle: 'white',
  },
})
